#!/bin/bash
# $Id: build-update-version-in-source.sh,v 1.2 2007-10-08 22:30:25 cvsuser Exp $

filename=content/const.js
cp $filename /tmp
sed "s#const APP_VERSION_NUMBER=.*#const APP_VERSION_NUMBER=\"$APP_VERSION_NUMBER\";   // this line generated by build.sh#" < $filename > asd
mv asd $filename
