#!/bin/bash
# $Id: build-update-version-in-source.sh,v 1.4 2007-11-26 19:52:09 cvsuser Exp $

filename=content/zindus/const.js
cp $filename /tmp
sed "s#const APP_VERSION_NUMBER=.*#const APP_VERSION_NUMBER=\"$APP_VERSION_NUMBER\";                      // this line generated by build.sh#" < $filename > asd
mv asd $filename
