function SyncFsmExitStatus()
{
	this.m_exit_status = null;
	this.m_fail_code   = null; // one of the Fail* codes
	this.m_fail_detail = null;
}

SyncFsmExitStatus.FailOnService   = 0; // some sort of service failure (generated by mozilla)
SyncFsmExitStatus.FailOnFault     = 1; // recived a soap fault
SyncFsmExitStatus.FailOnCancel    = 2; // user cancelled
SyncFsmExitStatus.FailOnUnknown   = 3; // this should never be!


SyncFsmExitStatus.prototype.toString = function()
{
	var ret = "";
	
	ret += "exit_status: " + this.m_exit_status;

	if (this.m_exit_status)
	{
		ret += " fail_code: "   + SyncFsmExitStatus.failCodeAsString(this.m_fail_code);
		ret += " fail_detail: " + this.m_fail_detail;
	}

	return ret;
}

SyncFsmExitStatus.failCodeAsString = function(code)
{
	var stringid = "status";

	switch(code)
	{
		case SyncFsmExitStatus.FailOnService: stringid += "FailOnService"; break;
		case SyncFsmExitStatus.FailOnFault:   stringid += "FailOnFault";   break;
		case SyncFsmExitStatus.FailOnCancel:  stringid += "FailOnCancel";  break;
		case SyncFsmExitStatus.FailOnUnknown: stringid += "FailOnUnknown"; break;
		default: cnsAssert(false);
	}

	return stringBundleString(stringid);
}
