/* ***** BEGIN LICENSE BLOCK *****
 * 
 * "The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 * 
 * The Original Code is Zindus Sync.
 * 
 * The Initial Developer of the Original Code is Moniker Pty Ltd.
 *
 * Portions created by Initial Developer are Copyright (C) 2007
 * the Initial Developer. All Rights Reserved.
 * 
 * Contributor(s): Leni Mayo
 * 
 * ***** END LICENSE BLOCK *****/

function SyncFsmExitStatus()
{
	this.m_exit_status      = null;
	this.m_fail_code        = null; // one of the Fail* codes
	this.m_fail_detail      = null;
	this.m_fail_soapmethod  = null;
	this.m_fail_fsmoldstate = null;
	this.m_count_conflicts  = 0;

	this.m_a_valid_code = {
		FailOnService                 : 0,  // some sort of service failure (generated by mozilla)
		FailOnFault                   : 1,  // recived a soap fault
		FailOnCancel                  : 2,  // user cancelled
		FailOnIntegrityBadCredentials : 3,  // something dodgy about url, username or password - dont proceed
		FailOnIntegrityDataStoreIn    : 4,  // something dodgy about url, username or password - dont proceed
		FailOnIntegrityDataStoreOut   : 5,  // something dodgy about url, username or password - dont proceed
		FailOnUnknown                 : 6,  // this should never be!
		FailOnFolderNameDuplicate     : 7,  // 
		FailOnFolderNameReserved      : 8,  // 
		FailOnFolderNameInvalid       : 9,
		FailOnFolderReservedChanged   : 10,
		FailOnFolderNameClash         : 11  // the same folder name entered the namespace from both tb and zm sides
	};
}

SyncFsmExitStatus.prototype.toString = function()
{
	var ret = "";
	
	ret += "exit_status: " + this.m_exit_status;

	if (this.m_exit_status)
	{
		ret += " fail_code: "        + this.failcode();
		ret += " fail_detail: "      + this.m_fail_detail;
		ret += " fail_fsmoldstate: " + this.m_fail_fsmoldstate;
	}

	ret += " count_conflicts: " + this.m_count_conflicts;

	return ret;
}

SyncFsmExitStatus.prototype.failCodeStringId = function()
{
	var stringid = "status" + this.failcode();

	return stringid;
}

SyncFsmExitStatus.prototype.failcode = function()
{
	if (arguments.length == 1)
	{
		this.m_fail_code = arguments[0];
		zinAssert(isPropertyPresent(this.m_a_valid_code, this.m_fail_code));
	}

	return this.m_fail_code;
}

SyncFsmExitStatus.prototype.isFailOnFolder = function()
{
	var code = this.failcode();

	var ret = ((code == 'FailOnFolderNameDuplicate') || (code == 'FailOnFolderNameReserved') ||
	           (code == 'FailOnFolderNameInvalid')   || (code == 'FailOnFolderReservedChanged') ||
	           (code == 'FailOnFolderNameClash'));

	return ret;
}
