/* ***** BEGIN LICENSE BLOCK *****
 * 
 * "The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 * 
 * The Original Code is Zindus Sync.
 * 
 * The Initial Developer of the Original Code is Moniker Pty Ltd.
 *
 * Portions created by Initial Developer are Copyright (C) 2007
 * the Initial Developer. All Rights Reserved.
 * 
 * Contributor(s): Leni Mayo
 * 
 * ***** END LICENSE BLOCK *****/

include("chrome://zindus/content/utils.js");

function SyncFsmExitStatus()
{
	this.m_exit_status      = null;
	this.m_fail_code        = null; // one of the Fail* codes
	this.m_fail_detail      = null;
	this.m_fail_soapmethod  = null;
	this.m_fail_fsmoldstate = null;
	this.m_count_conflicts  = 0;

	this.m_a_valid_code = {
		FailOnService                 : 0,  // some sort of service failure (generated by mozilla)
		FailOnFault                   : 1,  // recieved a soap fault
		FailOnMismatchedResponse      : 2,  // sent BlahRequest and received FooResponse (expected BlahResponse)
		FailOnCancel                  : 3,  // user cancelled
		FailOnIntegrityBadCredentials : 4,  // something dodgy about url, username or password - dont proceed
		FailOnIntegrityDataStoreIn    : 5,  // something dodgy about url, username or password - dont proceed
		FailOnIntegrityDataStoreOut   : 6,  // something dodgy about url, username or password - dont proceed
		FailOnUnknown                 : 7,  // this should never be!
		FailOnFolderNameDuplicate     : 8,  // 
		FailOnFolderNameReserved      : 9,  // 
		FailOnFolderNameInvalid       : 10,
		FailOnFolderMustBePresent     : 11,
		FailOnFolderReservedChanged   : 12,
		FailOnFolderNameClash         : 13  // the same folder name entered the namespace from both tb and zm sides
	};
}

SyncFsmExitStatus.prototype.stringBundleString = stringBundleString;

SyncFsmExitStatus.prototype.toString = function()
{
	var ret = "";
	
	ret += "exit_status: " + this.m_exit_status;

	if (this.m_exit_status)
	{
		ret += " fail_code: "        + this.failcode();
		ret += " fail_detail: "      + this.m_fail_detail;
		ret += " fail_fsmoldstate: " + this.m_fail_fsmoldstate;
	}

	ret += " count_conflicts: " + this.m_count_conflicts;

	return ret;
}

SyncFsmExitStatus.prototype.failCodeStringId = function()
{
	var stringid = "status" + this.failcode();

	return stringid;
}

SyncFsmExitStatus.prototype.failcode = function()
{
	if (arguments.length == 1)
	{
		this.m_fail_code = arguments[0];
		zinAssert(isPropertyPresent(this.m_a_valid_code, this.m_fail_code));
	}

	return this.m_fail_code;
}

SyncFsmExitStatus.prototype.isFailOnFolder = function()
{
	var code = this.failcode();

	var ret = ((code == 'FailOnFolderNameDuplicate') || (code == 'FailOnFolderNameReserved') ||
	           (code == 'FailOnFolderNameInvalid')   || (code == 'FailOnFolderReservedChanged') ||
	           (code == 'FailOnFolderMustBePresent') || (code == 'FailOnFolderNameClash'));

	return ret;
}

SyncFsmExitStatus.asMessage = function(context, sbsSuccess, sbsFailure)
{
	var msg = "";

	// if the dialog was cancelled while we were syncing, string bundles wont be available, so we try/catch...
	//
	try {
		if (context.m_exit_status == 0)
			msg += stringBundleString(sbsSuccess);
		else
		{
			msg += stringBundleString(sbsFailure);
			msg += "\n" + stringBundleString(context.failCodeStringId());

			if (context.failcode() == 'FailOnFault')
			{
				msg += "\n" + context.m_fail_detail;
				msg += "\n" + stringBundleString("statusFailSoapMethod") + " " + context.m_fail_soapmethod;
			}
			else if (context.failcode() == 'FailOnCancel')
				msg += "\n" + stringBundleString("statusFailOnCancelDetail");
			else if (context.failcode() == 'FailOnService')
				msg += "\n" + stringBundleString("statusFailOnServiceDetail");
			else if (context.isFailOnFolder())
				msg += ": " + context.m_fail_detail;  // add the name of the offending folder
		}
	} catch (ex) {
		dump("asMessage: exception: " + ex.message + "\n");
		newZinLogger("SyncFsmExitStatus").debug("asMessage: exception: " + ex.message);
	}

	return msg;
}

